FROM nginx:alpine

# Hapus konten default Nginx
RUN rm -rf /etc/nginx/conf.d/* /usr/share/nginx/html/*

# Salin file konfigurasi Nginx kustom
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Salin file frontend aplikasi Anda
COPY ./frontend /usr/share/nginx/html
COPY ./frontend/static /usr/share/nginx/html/static

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]